development: &default
  adapter: postgresql
  database: keeper_crm_development
  username:
  password:
  host:     localhost
  port:     5432
  schema_search_path: public
  min_messages: warning

test:
  <<: *default
  database: keeper_crm_test

production:
  <<: *default
  host:     192.168.0.164
  port:     5432
  database: keeper_crm_production
  username: crm_db
  password: evan123456

staging:
  <<: *default
  host:     192.168.0.164
  port:     5432
  database: keeper_crm_staging
  username: crm_db
  password: evan123456

